name: Android APK

on: [push, pull_request]

jobs:
  buildForAndroidPlatform:
    name: Build For Android Platform
    runs-on: ubuntu-latest
    steps:
      # Liberar espacio
      - name: Check free disk space
        uses: jlumbroso/free-disk-space@v1.3.1

      # Clonar repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Almacenar en cache la carpeta Library
      - name: Cache Android AAB
        uses: actions/cache@v4
        with:
          path: Library/Android_AAB
          key: Library-Android

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Generar build
      - name: Build Unity project for Android
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          # androidExportType: androidAppBundle
          # androidKeystoreName: user # This file won't exist, but this property needs to exist.
          # androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          # androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          # androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          # androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          androidTargetSdkVersion: AndroidApiLevel34

      # Subir artefacto
      - name: Upload Android build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-Android
          path: build/Android
