name: Actions 😎

on: [push, pull_request]

jobs:
  buildForAndroidPlatform:
    name: Build For Android Platform
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: Library/Android_AAB
          key: Library-Android
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          androidExportType: androidAppBundle
          androidKeystoreName: user # This file won't exist, but this property needs to exist.
          # androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          # androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          # androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          # androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          androidTargetSdkVersion: AndroidApiLevel35
      - uses: actions/upload-artifact@v3
        with:
          name: build-Android
          path: build/Android
