name: Test project

on: [push, pull_request]

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./
        testMode:
         # - playmode
          - editmode
    steps:
      # Checkout
      - name: Clonando el repositorio
        uses: actions/checkout@v4
        with:
          lfs: true
          
      # Cache
      - name: Almacenando Library en cache
        uses: actions/cache@v4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
            
      # Test
      - name: Probando
        uses: game-ci/unity-test-runner@v4.3.1
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*;dontClear'
          
      # Mostrar archivos de la raiz para ver si se encuentra la carpeta CodeCoverage
      - name: Listar archivos y directorios
        run: ls -l

      # Comprobar si existe la carpeta CodeCoverage
      - name: Verificar si el directorio existe
        run: |
          if [ ! -d ${{ steps.tests.outputs.coveragePath }} ]; then
            echo "El directorio no existe. Creándolo..."
            mkdir mi-directorio
          else
            echo "El directorio ya existe."
          fi

      # Intentar ver si es problema de permisos
      - name: Cambiar permisos de archivos de cobertura
        run: sudo chmod -R a+r "${{ steps.tests.outputs.coveragePath }}"
      
      # Mostrar contenido de CodeCoverage
      - name: Listar archivos y directorios de CodeCoverage
        run: ls -l ${{ steps.tests.outputs.coveragePath }}

      # Mostrar contenido de CodeCoverage
      - name: Listar archivos y directorios de editmode-artifacts
        run: ls -l ${{ steps.tests.outputs.artifactsPath }}

      # Mostrar nombre de rutas
      - name: Nombres de rutas
        run: echo "${{ steps.tests.outputs.artifactsPath }} -- ${{ steps.tests.outputs.coveragePath }} "
        
      # Test Artifacts
      - name: Almacenar resultados de las pruebas
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
          
      # Coverage Artifacts
      - name: Almacenar resultados del CodeCoverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Coverage results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.coveragePath }}/workspace-opencov/
